### ISSUE TITLE
Recipe Kanban Board

### ISSUE THREAD

**Issue by H-Ramalan** [H-Ramalan/recipe#11]
We are a group of two @HafizMassamTabraizKhan  and @H-Ramalan 
This is the link to our kanban board.
[Recipe Kanban Board](https://github.com/users/H-Ramalan/projects/3/views/2)

**Comment by shella12** [comment]
Hi @H-Ramalan and @HafizMassamTabraizKhan, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Created all required columns ✔️ 
- All requirements have a card in `To Do` ✔️ 
- All tasks are assigned  ✔️ 
- All cards are assigned fairly ✔️ 
- Cards are descriptive ✔️ 
- Implemented all requirements 👏 

## Optional suggestions

- [ ] [OPTIONAL] You have good titles for each To Do card however I would suggest using active verbs in your to-do card titles instead of noun phrases as this makes the title very descriptive and actionable. Here are a few suggestions for improvement:
Instead of "Food list", try "Create a food list" 
Instead of "Project setup", try "Set up the project" or "Initialize the project".
You can also use more specific verbs to describe the tasks you need to complete. For example, instead of "Login page and registration page", you could say "Implement the user login function" or "Implement the user registration feature".


<img width="358" alt="Screenshot 2023-10-23 at 2 32 47 PM" src="https://github.com/H-Ramalan/recipe/assets/44798044/62624379-88f5-4cec-b20c-1c9f32f1e042">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
